# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/tab_unit/tab_unit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabUnit(object):
    def setupUi(self, TabUnit):
        TabUnit.setObjectName("TabUnit")
        TabUnit.resize(599, 536)
        self.btn_unit_search = QtWidgets.QPushButton(TabUnit)
        self.btn_unit_search.setGeometry(QtCore.QRect(40, 40, 93, 28))
        self.btn_unit_search.setObjectName("btn_unit_search")

        self.retranslateUi(TabUnit)
        QtCore.QMetaObject.connectSlotsByName(TabUnit)

    def retranslateUi(self, TabUnit):
        _translate = QtCore.QCoreApplication.translate
        TabUnit.setWindowTitle(_translate("TabUnit", "Form"))
        self.btn_unit_search.setText(_translate("TabUnit", "组播搜索"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabUnit = QtWidgets.QWidget()
    ui = Ui_TabUnit()
    ui.setupUi(TabUnit)
    TabUnit.show()
    sys.exit(app.exec_())
