# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/sub_parse_index/parse_index.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParseIndex(object):
    def setupUi(self, ParseIndex):
        ParseIndex.setObjectName("ParseIndex")
        ParseIndex.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ParseIndex)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_open = QtWidgets.QPushButton(self.widget)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 6)
        self.verticalLayout.addWidget(self.widget)
        self.tab_list = QtWidgets.QTableWidget(self.centralwidget)
        self.tab_list.setObjectName("tab_list")
        self.tab_list.setColumnCount(6)
        self.tab_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_list.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tab_list)
        ParseIndex.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParseIndex)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ParseIndex.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParseIndex)
        self.statusbar.setObjectName("statusbar")
        ParseIndex.setStatusBar(self.statusbar)

        self.retranslateUi(ParseIndex)
        QtCore.QMetaObject.connectSlotsByName(ParseIndex)

    def retranslateUi(self, ParseIndex):
        _translate = QtCore.QCoreApplication.translate
        ParseIndex.setWindowTitle(_translate("ParseIndex", "MainWindow"))
        self.label.setText(_translate("ParseIndex", "请选择索引文件:"))
        self.btn_open.setText(_translate("ParseIndex", "打开"))
        item = self.tab_list.horizontalHeaderItem(0)
        item.setText(_translate("ParseIndex", "新建列"))
        item = self.tab_list.horizontalHeaderItem(1)
        item.setText(_translate("ParseIndex", "开始时间"))
        item = self.tab_list.horizontalHeaderItem(2)
        item.setText(_translate("ParseIndex", "结束时间"))
        item = self.tab_list.horizontalHeaderItem(3)
        item.setText(_translate("ParseIndex", "文件大小(MB)"))
        item = self.tab_list.horizontalHeaderItem(4)
        item.setText(_translate("ParseIndex", "平均码率(KB/s)"))
        item = self.tab_list.horizontalHeaderItem(5)
        item.setText(_translate("ParseIndex", "时长(sec)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ParseIndex = QtWidgets.QMainWindow()
    ui = Ui_ParseIndex()
    ui.setupUi(ParseIndex)
    ParseIndex.show()
    sys.exit(app.exec_())
