# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/sub_splicing/splicing.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Splice(object):
    def setupUi(self, Splice):
        Splice.setObjectName("Splice")
        Splice.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Splice)
        self.centralwidget.setObjectName("centralwidget")
        Splice.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Splice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Splice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Splice)
        self.statusbar.setObjectName("statusbar")
        Splice.setStatusBar(self.statusbar)

        self.retranslateUi(Splice)
        QtCore.QMetaObject.connectSlotsByName(Splice)

    def retranslateUi(self, Splice):
        _translate = QtCore.QCoreApplication.translate
        Splice.setWindowTitle(_translate("Splice", "拼接调试工具"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Splice = QtWidgets.QMainWindow()
    ui = Ui_Splice()
    ui.setupUi(Splice)
    Splice.show()
    sys.exit(app.exec_())
