# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/tab_dev/tab_dev.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabDev(object):
    def setupUi(self, TabDev):
        TabDev.setObjectName("TabDev")
        TabDev.resize(400, 300)
        self.label = QtWidgets.QLabel(TabDev)
        self.label.setGeometry(QtCore.QRect(40, 40, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(TabDev)
        QtCore.QMetaObject.connectSlotsByName(TabDev)

    def retranslateUi(self, TabDev):
        _translate = QtCore.QCoreApplication.translate
        TabDev.setWindowTitle(_translate("TabDev", "Form"))
        self.label.setText(_translate("TabDev", "RTSP地址"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabDev = QtWidgets.QWidget()
    ui = Ui_TabDev()
    ui.setupUi(TabDev)
    TabDev.show()
    sys.exit(app.exec_())
